# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import loffi.models


class Migration(migrations.Migration):

    dependencies = [
        ('loffi', '0002_auto_20160505_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='size_x',
            field=models.FloatField(default=0, help_text='миллиметров, мм', verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='size_y',
            field=models.FloatField(default=0, help_text='миллиметров, мм', verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='size_z',
            field=models.FloatField(blank=True, default=0, help_text='миллиметров, мм', null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='itemsubclass',
            name='title_single',
            field=models.CharField(blank=True, help_text='Для использования в отдельных объектах', max_length=50, null=True, verbose_name='Название в единственном числе'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=loffi.models.Status(4, 'Не обработан', 'Заказ поступил в базу,но не был обработан администратором'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='loffi.Status', verbose_name='Статус заказа'),
        ),
    ]
