# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loffi', '0003_auto_20160508_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_read',
            field=models.BooleanField(default=True, verbose_name='Прочитано'),
        ),
    ]
